/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkbenchRouteImport } from './routes/workbench'
import { Route as VoicesRouteImport } from './routes/voices'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NewBookIndexRouteImport } from './routes/new-book/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as LibraryBookSlugIndexRouteImport } from './routes/library/$bookSlug/index'
import { Route as LibraryBookSlugDocumentIdRouteImport } from './routes/library/$bookSlug/$documentId'
import { Route as LibraryBookSlugDocumentIdIndexRouteImport } from './routes/library/$bookSlug/$documentId/index'
import { Route as LibraryBookSlugDocumentIdTextRouteImport } from './routes/library/$bookSlug/$documentId/text'
import { Route as LibraryBookSlugDocumentIdSynthesisRouteImport } from './routes/library/$bookSlug/$documentId/synthesis'
import { Route as LibraryBookSlugDocumentIdCastRouteImport } from './routes/library/$bookSlug/$documentId/cast'

const WorkbenchRoute = WorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => rootRouteImport,
} as any)
const VoicesRoute = VoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBookIndexRoute = NewBookIndexRouteImport.update({
  id: '/new-book/',
  path: '/new-book/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBookSlugIndexRoute = LibraryBookSlugIndexRouteImport.update({
  id: '/library/$bookSlug/',
  path: '/library/$bookSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryBookSlugDocumentIdRoute =
  LibraryBookSlugDocumentIdRouteImport.update({
    id: '/library/$bookSlug/$documentId',
    path: '/library/$bookSlug/$documentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const LibraryBookSlugDocumentIdIndexRoute =
  LibraryBookSlugDocumentIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LibraryBookSlugDocumentIdRoute,
  } as any)
const LibraryBookSlugDocumentIdTextRoute =
  LibraryBookSlugDocumentIdTextRouteImport.update({
    id: '/text',
    path: '/text',
    getParentRoute: () => LibraryBookSlugDocumentIdRoute,
  } as any)
const LibraryBookSlugDocumentIdSynthesisRoute =
  LibraryBookSlugDocumentIdSynthesisRouteImport.update({
    id: '/synthesis',
    path: '/synthesis',
    getParentRoute: () => LibraryBookSlugDocumentIdRoute,
  } as any)
const LibraryBookSlugDocumentIdCastRoute =
  LibraryBookSlugDocumentIdCastRouteImport.update({
    id: '/cast',
    path: '/cast',
    getParentRoute: () => LibraryBookSlugDocumentIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/voices': typeof VoicesRoute
  '/workbench': typeof WorkbenchRoute
  '/library/': typeof LibraryIndexRoute
  '/new-book/': typeof NewBookIndexRoute
  '/library/$bookSlug/$documentId': typeof LibraryBookSlugDocumentIdRouteWithChildren
  '/library/$bookSlug/': typeof LibraryBookSlugIndexRoute
  '/library/$bookSlug/$documentId/cast': typeof LibraryBookSlugDocumentIdCastRoute
  '/library/$bookSlug/$documentId/synthesis': typeof LibraryBookSlugDocumentIdSynthesisRoute
  '/library/$bookSlug/$documentId/text': typeof LibraryBookSlugDocumentIdTextRoute
  '/library/$bookSlug/$documentId/': typeof LibraryBookSlugDocumentIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/voices': typeof VoicesRoute
  '/workbench': typeof WorkbenchRoute
  '/library': typeof LibraryIndexRoute
  '/new-book': typeof NewBookIndexRoute
  '/library/$bookSlug': typeof LibraryBookSlugIndexRoute
  '/library/$bookSlug/$documentId/cast': typeof LibraryBookSlugDocumentIdCastRoute
  '/library/$bookSlug/$documentId/synthesis': typeof LibraryBookSlugDocumentIdSynthesisRoute
  '/library/$bookSlug/$documentId/text': typeof LibraryBookSlugDocumentIdTextRoute
  '/library/$bookSlug/$documentId': typeof LibraryBookSlugDocumentIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/voices': typeof VoicesRoute
  '/workbench': typeof WorkbenchRoute
  '/library/': typeof LibraryIndexRoute
  '/new-book/': typeof NewBookIndexRoute
  '/library/$bookSlug/$documentId': typeof LibraryBookSlugDocumentIdRouteWithChildren
  '/library/$bookSlug/': typeof LibraryBookSlugIndexRoute
  '/library/$bookSlug/$documentId/cast': typeof LibraryBookSlugDocumentIdCastRoute
  '/library/$bookSlug/$documentId/synthesis': typeof LibraryBookSlugDocumentIdSynthesisRoute
  '/library/$bookSlug/$documentId/text': typeof LibraryBookSlugDocumentIdTextRoute
  '/library/$bookSlug/$documentId/': typeof LibraryBookSlugDocumentIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/voices'
    | '/workbench'
    | '/library/'
    | '/new-book/'
    | '/library/$bookSlug/$documentId'
    | '/library/$bookSlug/'
    | '/library/$bookSlug/$documentId/cast'
    | '/library/$bookSlug/$documentId/synthesis'
    | '/library/$bookSlug/$documentId/text'
    | '/library/$bookSlug/$documentId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/voices'
    | '/workbench'
    | '/library'
    | '/new-book'
    | '/library/$bookSlug'
    | '/library/$bookSlug/$documentId/cast'
    | '/library/$bookSlug/$documentId/synthesis'
    | '/library/$bookSlug/$documentId/text'
    | '/library/$bookSlug/$documentId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/voices'
    | '/workbench'
    | '/library/'
    | '/new-book/'
    | '/library/$bookSlug/$documentId'
    | '/library/$bookSlug/'
    | '/library/$bookSlug/$documentId/cast'
    | '/library/$bookSlug/$documentId/synthesis'
    | '/library/$bookSlug/$documentId/text'
    | '/library/$bookSlug/$documentId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  VoicesRoute: typeof VoicesRoute
  WorkbenchRoute: typeof WorkbenchRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  NewBookIndexRoute: typeof NewBookIndexRoute
  LibraryBookSlugDocumentIdRoute: typeof LibraryBookSlugDocumentIdRouteWithChildren
  LibraryBookSlugIndexRoute: typeof LibraryBookSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workbench': {
      id: '/workbench'
      path: '/workbench'
      fullPath: '/workbench'
      preLoaderRoute: typeof WorkbenchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voices': {
      id: '/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof VoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-book/': {
      id: '/new-book/'
      path: '/new-book'
      fullPath: '/new-book/'
      preLoaderRoute: typeof NewBookIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library/'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$bookSlug/': {
      id: '/library/$bookSlug/'
      path: '/library/$bookSlug'
      fullPath: '/library/$bookSlug/'
      preLoaderRoute: typeof LibraryBookSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$bookSlug/$documentId': {
      id: '/library/$bookSlug/$documentId'
      path: '/library/$bookSlug/$documentId'
      fullPath: '/library/$bookSlug/$documentId'
      preLoaderRoute: typeof LibraryBookSlugDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$bookSlug/$documentId/': {
      id: '/library/$bookSlug/$documentId/'
      path: '/'
      fullPath: '/library/$bookSlug/$documentId/'
      preLoaderRoute: typeof LibraryBookSlugDocumentIdIndexRouteImport
      parentRoute: typeof LibraryBookSlugDocumentIdRoute
    }
    '/library/$bookSlug/$documentId/text': {
      id: '/library/$bookSlug/$documentId/text'
      path: '/text'
      fullPath: '/library/$bookSlug/$documentId/text'
      preLoaderRoute: typeof LibraryBookSlugDocumentIdTextRouteImport
      parentRoute: typeof LibraryBookSlugDocumentIdRoute
    }
    '/library/$bookSlug/$documentId/synthesis': {
      id: '/library/$bookSlug/$documentId/synthesis'
      path: '/synthesis'
      fullPath: '/library/$bookSlug/$documentId/synthesis'
      preLoaderRoute: typeof LibraryBookSlugDocumentIdSynthesisRouteImport
      parentRoute: typeof LibraryBookSlugDocumentIdRoute
    }
    '/library/$bookSlug/$documentId/cast': {
      id: '/library/$bookSlug/$documentId/cast'
      path: '/cast'
      fullPath: '/library/$bookSlug/$documentId/cast'
      preLoaderRoute: typeof LibraryBookSlugDocumentIdCastRouteImport
      parentRoute: typeof LibraryBookSlugDocumentIdRoute
    }
  }
}

interface LibraryBookSlugDocumentIdRouteChildren {
  LibraryBookSlugDocumentIdCastRoute: typeof LibraryBookSlugDocumentIdCastRoute
  LibraryBookSlugDocumentIdSynthesisRoute: typeof LibraryBookSlugDocumentIdSynthesisRoute
  LibraryBookSlugDocumentIdTextRoute: typeof LibraryBookSlugDocumentIdTextRoute
  LibraryBookSlugDocumentIdIndexRoute: typeof LibraryBookSlugDocumentIdIndexRoute
}

const LibraryBookSlugDocumentIdRouteChildren: LibraryBookSlugDocumentIdRouteChildren =
  {
    LibraryBookSlugDocumentIdCastRoute: LibraryBookSlugDocumentIdCastRoute,
    LibraryBookSlugDocumentIdSynthesisRoute:
      LibraryBookSlugDocumentIdSynthesisRoute,
    LibraryBookSlugDocumentIdTextRoute: LibraryBookSlugDocumentIdTextRoute,
    LibraryBookSlugDocumentIdIndexRoute: LibraryBookSlugDocumentIdIndexRoute,
  }

const LibraryBookSlugDocumentIdRouteWithChildren =
  LibraryBookSlugDocumentIdRoute._addFileChildren(
    LibraryBookSlugDocumentIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  VoicesRoute: VoicesRoute,
  WorkbenchRoute: WorkbenchRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  NewBookIndexRoute: NewBookIndexRoute,
  LibraryBookSlugDocumentIdRoute: LibraryBookSlugDocumentIdRouteWithChildren,
  LibraryBookSlugIndexRoute: LibraryBookSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
